2022-07-08 10:23:05,153 | INFO | Check successful
2022-07-08 10:23:05,176 | ERROR | The following unhandled exception occured :
Traceback (most recent call last):
  File "C:\Users\tojak\anaconda3\envs\labeq\lib\site-packages\exopy\tasks\tasks\base_tasks.py", line 1148, in perform
    child.perform_()
  File "C:\Users\tojak\anaconda3\envs\labeq\lib\site-packages\exopy\tasks\tasks\decorators.py", line 86, in decorator
    return function_to_decorate(*args, **kwargs)
  File "c:\users\tojak\source\repos\labeq-exopy\src\labeq_exopy\tasks\tasks\instr\yokogawaGS200_tasks.py", line 69, in perform
    value = self.format_and_eval_string(self.set_range_val)
  File "C:\Users\tojak\anaconda3\envs\labeq\lib\site-packages\exopy\tasks\tasks\base_tasks.py", line 502, in format_and_eval_string
    return safe_eval(string, {})
  File "C:\Users\tojak\anaconda3\envs\labeq\lib\site-packages\exopy\tasks\tasks\string_evaluation.py", line 48, in safe_eval
    return eval(expr, globals(), local_var)
  File "<string>", line 1, in <module>
NameError: name 'MIN' is not defined
2022-07-08 10:23:07,185 | INFO | Process shuting down
