2022-07-01 15:56:16,507 | INFO | Check successful
2022-07-01 15:56:16,529 | CRITICAL | C:\Users\tojak\anaconda3\envs\labeq\lib\site-packages\pyvisa\resources\messagebased.py:642: UserWarning: write message already ends with termination characters
  self.write(message)
2022-07-01 15:56:16,575 | INFO | value : -2.496011E-11
2022-07-01 15:56:16,579 | INFO | Iterating connection 0/2 for instrument Keithley6500
2022-07-01 15:56:16,605 | INFO | Iterating connection 1/2 for instrument Keithley6500
2022-07-01 15:56:16,628 | INFO | Iterating connection 0/2 for instrument Keithley6500
2022-07-01 15:56:16,651 | INFO | Iterating connection 0/2 for instrument Keithley6500
2022-07-01 15:56:16,675 | INFO | Iterating connection 1/2 for instrument Keithley6500
2022-07-01 15:56:16,700 | INFO | Iterating connection 1/2 for instrument Keithley6500
2022-07-01 15:56:16,729 | INFO | Iterating connection 0/2 for instrument Keithley6500
2022-07-01 15:56:16,753 | INFO | Iterating connection 1/2 for instrument Keithley6500
2022-07-01 15:56:16,780 | ERROR | The following unhandled exception occured :
Traceback (most recent call last):
  File "C:\Users\tojak\anaconda3\envs\labeq\lib\site-packages\exopy\tasks\tasks\base_tasks.py", line 1148, in perform
    child.perform_()
  File "C:\Users\tojak\anaconda3\envs\labeq\lib\site-packages\exopy\tasks\tasks\decorators.py", line 86, in decorator
    return function_to_decorate(*args, **kwargs)
  File "C:\Users\tojak\anaconda3\envs\labeq\lib\site-packages\exopy\tasks\tasks\decorators.py", line 307, in wrapper
    return perform(obj, *args, **kwargs)
  File "c:\users\tojak\source\repos\labeq-exopy\src\labeq_exopy\tasks\tasks\instr\meas_acvoltage_tasks.py", line 39, in perform
    value = self.driver.read_voltage_ac()
  File "c:\users\tojak\source\repos\labeq-exopy\src\labeq_exopy\instruments\drivers\driver_tools.py", line 126, in wrapper
    return method(self, *args, **kwargs)
  File "c:\users\tojak\source\repos\labeq-exopy\src\labeq_exopy\instruments\drivers\visa\KeithleyDMM6500DigitMultimeter_driver.py", line 129, in read_voltage_ac
    self.function = 'VOLT:AC'
  File "c:\users\tojak\source\repos\labeq-exopy\src\labeq_exopy\instruments\drivers\driver_tools.py", line 101, in __set__
    super(instrument_property, self).__set__(obj, value)
  File "c:\users\tojak\source\repos\labeq-exopy\src\labeq_exopy\instruments\drivers\driver_tools.py", line 126, in wrapper
    return method(self, *args, **kwargs)
  File "c:\users\tojak\source\repos\labeq-exopy\src\labeq_exopy\instruments\drivers\visa\KeithleyDMM6500DigitMultimeter_driver.py", line 87, in function
    raise InstrIOError('Keithley6500: Failed to set function')
labeq_exopy.instruments.drivers.driver_tools.InstrIOError: Keithley6500: Failed to set function
2022-07-01 15:56:18,788 | INFO | Process shuting down
