2022-07-06 15:27:59,098 | INFO | Check successful
2022-07-06 15:27:59,125 | ERROR | The following unhandled exception occured :
Traceback (most recent call last):
  File "C:\Users\tojak\anaconda3\envs\labeq\lib\site-packages\exopy\tasks\tasks\base_tasks.py", line 1148, in perform
    child.perform_()
  File "C:\Users\tojak\anaconda3\envs\labeq\lib\site-packages\exopy\tasks\tasks\decorators.py", line 86, in decorator
    return function_to_decorate(*args, **kwargs)
  File "C:\Users\tojak\anaconda3\envs\labeq\lib\site-packages\exopy\tasks\tasks\decorators.py", line 307, in wrapper
    return perform(obj, *args, **kwargs)
  File "c:\users\tojak\source\repos\labeq-exopy\src\labeq_exopy\tasks\tasks\instr\meas_dccurrent_tasks.py", line 39, in perform
    value = self.driver.read_current_dc()
AttributeError: 'YokogawaGS200' object has no attribute 'read_current_dc'
2022-07-06 15:28:01,143 | INFO | Process shuting down
